2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_setup.py:_flush():68] Configure stats pid to 283454
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_setup.py:_flush():68] Loading settings from /home/lawrence/.config/wandb/settings
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_setup.py:_flush():68] Loading settings from /home/lawrence/llava-interpret/wandb/settings
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_init.py:_log_setup():528] Logging user logs to /home/lawrence/llava-interpret/wandb/run-20241211_192059-qxaleu0h/logs/debug.log
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_init.py:_log_setup():529] Logging internal logs to /home/lawrence/llava-interpret/wandb/run-20241211_192059-qxaleu0h/logs/debug-internal.log
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_init.py:init():639] calling init triggers
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {'embedding_dim': 4096, 'expansion_factor': 8, 'hidden_dim': 32768, 'penalty_coeff': 0.05, 'learning_rate': 0.0001, 'batch_tokens': 32, 'batch_size': 128, 'num_epochs': 10}
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_init.py:init():688] starting backend
2024-12-11 19:20:59,292 INFO    MainThread:283454 [wandb_init.py:init():692] sending inform_init request
2024-12-11 19:20:59,297 INFO    MainThread:283454 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-11 19:20:59,297 INFO    MainThread:283454 [wandb_init.py:init():705] backend started and connected
2024-12-11 19:20:59,299 INFO    MainThread:283454 [wandb_init.py:init():798] updated telemetry
2024-12-11 19:20:59,302 INFO    MainThread:283454 [wandb_init.py:init():830] communicating run to backend with 90.0 second timeout
2024-12-11 19:20:59,494 ERROR   MainThread:283454 [wandb_init.py:init():857] encountered error: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-11 19:20:59,494 ERROR   MainThread:283454 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/home/lawrence/anaconda3/envs/interp/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/lawrence/anaconda3/envs/interp/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 863, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-11 19:20:59,502 WARNING MsgRouterThr:283454 [router.py:message_loop():75] message_loop has been closed
